project:
  type: website

website:
  title: "North American Aquatic Energy Density Toolbox (NAAEDT)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



